package com.java.exception;

public class ExceptionWithFinalBlock {
	int i = 20;
	String myName = null;
	public static void main(String args[]) {
		try {
			 
			}catch(NullPointerException ex) {
				System.out.println(ex);
			
			
		}
		
		
	}
	

}
